FROM node:20
WORKDIR /usr/src/app
COPY package.json package-lock.json* tsconfig.json ./
RUN npm install
COPY src ./src
RUN npx tsc
EXPOSE 3000
CMD ["node","dist/src/adapters/input/rest/TranslateRestAdapter.js"] 
