version: "3.9"

services:
  word-translator-service:
    build: .
    container_name: word-translator-service
    ports:
      - "8000:8000"
    depends_on:
      - redis
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - REDIS_PREFIX=translator:word:
  redis:
    image: redis:7
    container_name: translator-redis
    ports:
      - "6379:6379"
