version: "3.9"

services:
  word-translator-service-node:
    build: .
    container_name: word-translator-service-node
    ports:
      - "3000:3000"
    depends_on:
      - redis
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - REDIS_PREFIX=translator:word:
  redis:
    image: redis:7
    container_name: translator-redis
    ports:
      - "6379:6379"
